Use su when sudo isn't available (see notes).
So that impersonating --user remains possible.

Note: Passing arguments that include interior white space to su -c
<command arguments...> won't work. This is a limitation of the way su
constructs the -c option argument. This limitation could be removed with
more complicated code, which would rarely be used. Work-arounds: don't
embed spaces in command arguments; use a script file; use sudo.

Note: When --firejail is used, the command must be a simple command,
not a shell command list.

diff --git a/torjail b/torjail
--- a/torjail
+++ b/torjail
@@ -176,7 +176,11 @@ if [ "$1" = "--inside" ]; then
 
   print G " * Executing..."
 
-  ${SUDOBIN:+$SUDOBIN -u $USERNAME} "$@" || error "Execution failed."
+  if [ "$SUDOBIN" ]; then
+    $SUDOBIN -u $USERNAME "$@"
+  else
+    su $USERNAME -c "$*"
+  fi || error "Execution failed."
   exit
 fi
 
@@ -306,7 +310,7 @@ if [ $USEFIREJAIL = y ]; then
 fi
 
 err=0
-for cmd in ip iptables tor $FIREJAILBIN; do
+for cmd in ip iptables tor $FIREJAILBIN ${SUDOBIN:-su}; do
   if ! [ file = "$(type -t $cmd 2>/dev/null)" ]; then
     printv R "$cmd isn't a command file"
     err=1
@@ -438,7 +442,11 @@ chmod a+r $RESOLVEFILE || die "Failed to change permissions to $RESOLVEFILE"
 
 # use firejail as security container
 if [ $USEFIREJAIL = y ]; then
-  ${SUDOBIN:+$SUDOBIN -u $USERNAME} firejail --dns=$IPHOST --netns=$NAME "$@"
+  if [ "$SUDOBIN" ]; then
+    $SUDOBIN -u $USERNAME firejail --dns=$IPHOST --netns=$NAME "$@"
+  else
+    su $USERNAME -c "firejail --dns=$IPHOST --netns=$NAME $*"
+  fi
 else #or without
   ip netns exec $NAME \
     unshare --ipc --fork --pid --mount --mount-proc \
