add SIGINT exit handler

diff --git a/torjail b/torjail
--- a/torjail
+++ b/torjail
@@ -56,7 +56,34 @@ printvn() {
   VERBOSE=$OLDVERBOSE
 }
 
+# Handler of namespace, tor and resolve file
+cleanup() {
+  # removing the namespace
+  if [ "$KEEP" = y ]; then
+    print G " * Keeping the tor process $TORPID running"
+    print G " * Keeping the namespace $NAME"
+  else
     if [ "$TOREXEC" = y ]; then
+      print G " * Killing tor process $TORPID"
+      kill -9 $TORPID &> /dev/null
+      wait $! &> /dev/null
+      print G " * Killed $TORPID"
+    fi
+    print G " * Delete network namespace $NAME"
+    ip netns delete $NAME
+  fi
+
+  print G " * Removing the temporary resolve file $RESOLVEFILE..."
+  rm "$RESOLVEFILE"
+}
+
+# Handler of the interrupt signal
+interrupted() {
+  printv R " * Received stop signal"
+  cleanup
+  exit 1
+}
+
 help_and_exit() {
   VERBOSE=y
   printn N "Usage: "
@@ -104,6 +131,9 @@ fi
 
 # The tool
 # ~~~~~~~~
+
+# Call cleanup on ctrl-c (SIGINT)
+trap interrupted SIGINT
 
 # Arguments check
 while [[ $# -gt 0 ]]; do
@@ -290,22 +320,7 @@ ip netns exec $NAME \
   unshare --ipc --fork --pid --mount --mount-proc \
   $0 --inside "$USERNAME" "$RESOLVEFILE" "$VERBOSE" $*
 
-# removing the namespace
-if [ "$KEEP" = y ]; then
-  print G " * Keeping the tor process $TORPID running"
-  print G " * Keeping the namespace $NAME"
-else
-  if [ $TOREXEC = y ]; then
-    print G " * Killing tor process $TORPID"
-    kill -9 $TORPID &> /dev/null
-    wait $! &> /dev/null
-    print G " * Killed $TORPID"
-  fi
-  print G " * Delete network namespace $NAME"
-  ip netns delete $NAME
-fi
-
-print G " * Removing the temporary resolve file $RESOLVEFILE..."
-rm "$RESOLVEFILE"
+# clean some shit
+cleanup
 
 # All done!
